<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-G2U6CJJ" failures="5" tests="6" name="GroupAPITestRunner" time="1.415" errors="0" timestamp="2023-12-14T05:01:50 EST" skipped="0">
  <testcase classname="GroupAPITestRunner" name="runScenario" time="0.023">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDef.api.group.CreateGroupStepsAPI.iAmLoggedInAsAnAdminWithUsernameAndPassword(CreateGroupStepsAPI.java:19)
at ✽.I am logged in as an admin with "admin" and "admin" and create a group with the name "paid-jira-user"(classpath:features/api/group/a-create-groups-api.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="GroupAPITestRunner" name="runScenario" time="0.026">
    <failure message="expected [201] but found [401]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDef.api.group.AddUserToGroupStepsAPI.iAmLoggedInAsAnAdminWithUsernameAndPasswordAndAddAUserAddedUserToTheGroupNameGroup(AddUserToGroupStepsAPI.java:18)
at ✽.I am logged in as an admin with "bob" and "bob123" and add a user "jzjz" to the "paid-jira-user" group(classpath:features/api/group/b-assign-users-to-group-api.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="GroupAPITestRunner" name="runScenario" time="0.028">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDef.api.group.AddUserToGroupStepsAPI.iAmLoggedInAsAnAdminWithUsernameAndPasswordAndAddAUserAddedUserToTheGroupNameGroup(AddUserToGroupStepsAPI.java:18)
at ✽.I am logged in as an admin with "jzjz" and "jzjz" and add a user "bob" to the "basic-jira-user" group(classpath:features/api/group/b-assign-users-to-group-api.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="GroupAPITestRunner" name="runScenario" time="1.290">
    <failure message="expected [201] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDef.api.group.CreateGroupStepsAPI.iAmLoggedInAsAnAdminWithUsernameAndPassword(CreateGroupStepsAPI.java:19)
at ✽.I am logged in as an admin with "jzjz" and "jzjz" and create a group with the name "basic-jira-user"(classpath:features/api/group/a-create-groups-api.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="GroupAPITestRunner" name="runScenario" time="0.022">
    <failure message="expected [200] but found [401]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at stepDef.api.group.FilterUsersByGroupStepsAPI.iShouldReceiveAStatusCode(FilterUsersByGroupStepsAPI.java:18)
at ✽.I should receive a 200 status code(classpath:features/api/group/c-filter-user-by-group-api.feature:5)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="GroupAPITestRunner" name="runScenario" time="0.026"/>
</testsuite> <!-- GroupAPITestRunner -->
